Update types.hpp
*Why*
When trying to compile I get this error  
```./utilities/types.hpp:37:10: fatal error: json.hpp: No such file or directory
 ```
On further investigation it seems the file has been moved to headers in the third-party directory

*How* 
Simple fix is to add the headers dir